// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgdiWShZDgHw92xOh0Lvu6uUVBA-DcrL8',
    appId: '1:120670360500:android:33191ad0344bdecd0e58e1',
    messagingSenderId: '120670360500',
    projectId: 'yemi-login',
    storageBucket: 'yemi-login.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTdfycvpvdRkYC_ePKbe6szPv_oXGNgp8',
    appId: '1:120670360500:ios:1589059c464317260e58e1',
    messagingSenderId: '120670360500',
    projectId: 'yemi-login',
    storageBucket: 'yemi-login.firebasestorage.app',
    androidClientId: '120670360500-6brjkifs4ips9qlc20777r1ekfuucja8.apps.googleusercontent.com',
    iosClientId: '120670360500-26e5koc18sc9u6dmva83ic39cbbqt99l.apps.googleusercontent.com',
    iosBundleId: 'com.example.yemi',
  );

}